# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [113]:
# Create a 1-dimensional NumPy array using np.array()
array_1 = np.array([1, 2, 3, 4])

# Create a 2-dimensional NumPy array using np.array()
array_2 = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8,]])

# Create a 3-dimensional Numpy array using np.array()
array_3 = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]]])

In [7]:
array_1

array([1, 2, 3, 4])

In [8]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [114]:
array_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [116]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1.size, array_1.shape, array_1.ndim, array_1.dtype, type(array_1)

(4, (4,), 1, dtype('int32'), numpy.ndarray)

In [117]:
# Attributes of 2-dimensional array
array_2.size, array_2.shape, array_2.ndim, array_2.dtype, type(array_1)

(8, (2, 4), 2, dtype('int32'), numpy.ndarray)

In [118]:
# Attributes of 3-dimensional array
array_3.size, array_3.shape, array_3.ndim, array_3.dtype, type(array_1)

(18, (2, 3, 3), 3, dtype('int32'), numpy.ndarray)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
number = pd.DataFrame(array_2.T,
                     index=['Day 1','Day 2','Day 3','Day 4'],
                     columns=['Almond butter','Peanut Butter'])
number

Almond butter  Peanut Butter
Day 1              1              5
Day 2              2              6
Day 3              3              7
Day 4              4              8

In [28]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [33]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10, size=(7,2))

array([[3, 7],
       [1, 9],
       [7, 1],
       [2, 9],
       [7, 7],
       [1, 5],
       [6, 2]])

In [34]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random(size=(3,5))

array([[0.51305656, 0.34565176, 0.31750497, 0.4625266 , 0.86840703],
       [0.31015029, 0.43322506, 0.93360699, 0.59088815, 0.14076905],
       [0.58488928, 0.98543208, 0.6232309 , 0.78403971, 0.15581854]])

In [42]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [46]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_1 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_1)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [47]:
# Find the 0'th index of the latest array you created
random_1[0]

array([9, 7, 9, 8, 2, 1, 7])

In [48]:
# Get the first 2 rows of latest array you created
random_1[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [119]:
# Get the first 2 values of the first 2 rows of the latest array
random_1[:2, :2]

array([[9, 7],
       [7, 8]])

In [55]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_2 = np.random.randint(0,10,size=(3,5))
ones_1 = np.ones((3,5))

In [57]:
random_2

array([[5, 1, 9, 8, 4],
       [5, 3, 9, 6, 8],
       [6, 0, 0, 8, 8]])

In [58]:
ones_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# Add the two arrays together
both = random_2 + ones_1
both

array([[ 6.,  2., 10.,  9.,  5.],
       [ 6.,  4., 10.,  7.,  9.],
       [ 7.,  1.,  1.,  9.,  9.]])

In [59]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5,3))

In [63]:
# Try add the array of ones and the other most recent array together
ones_2 + both

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [64]:
# Create another array of ones of shape (3, 5)
ones_3 = np.ones((3,5))
ones_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [120]:
# Subtract the new array of ones from the other most recent array
random_2 - ones_1

array([[ 4.,  0.,  8.,  7.,  3.],
       [ 4.,  2.,  8.,  5.,  7.],
       [ 5., -1., -1.,  7.,  7.]])

In [121]:
# Multiply the ones array with the latest array
random_2 * ones_1

array([[5., 1., 9., 8., 4.],
       [5., 3., 9., 6., 8.],
       [6., 0., 0., 8., 8.]])

In [122]:
# Take the latest array to the power of 2 using '**'
random_2 ** random_2

array([[     3125,         1, 387420489,  16777216,       256],
       [     3125,        27, 387420489,     46656,  16777216],
       [    46656,         1,         1,  16777216,  16777216]],
      dtype=int32)

In [123]:
# Do the same thing with np.square()
np.square(random_2)

array([[25,  1, 81, 64, 16],
       [25,  9, 81, 36, 64],
       [36,  0,  0, 64, 64]], dtype=int32)

In [124]:
# Find the mean of the latest array using np.mean()
np.mean(random_2)

5.333333333333333

In [125]:
# Find the maximum of the latest array using np.max()
np.max(random_2)

9

In [126]:
# Find the minimum of the latest array using np.min()
np.min(random_2)

0

In [127]:
# Find the standard deviation of the latest array
np.std(random_2)

3.0477678535099892

In [128]:
# Find the variance of the latest array
np.var(random_2)

9.288888888888888

In [129]:
# Reshape the latest array to (3, 5, 1)
random_2.reshape(3,5,1)

array([[[5],
        [1],
        [9],
        [8],
        [4]],

       [[5],
        [3],
        [9],
        [6],
        [8]],

       [[6],
        [0],
        [0],
        [8],
        [8]]])

In [130]:
# Transpose the latest array
random_2.T
random_2

array([[5, 1, 9, 8, 4],
       [5, 3, 9, 6, 8],
       [6, 0, 0, 8, 8]])

What does the transpose do?

In [80]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_one = np.random.randint(0,10,size=(3,3))
array_two = np.random.randint(0,10,size=(3,2))

In [81]:
# Perform a dot product on the two newest arrays you created
array_one.dot(array_two)
# the other ways np.dot(array_one, array_two)

array([[ 76,  83],
       [ 96, 135],
       [ 44,  92]])

In [82]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_three = np.random.randint(0,10,size=(4,3))
array_four = np.random.randint(0,10,size=(4,3))

In [83]:
# Perform a dot product on the two newest arrays you created
array_three.dot(array_four)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [84]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
array_three.dot(array_four.T)

array([[ 0,  3, 12,  6],
       [ 6, 60, 36, 45],
       [ 0, 11,  4,  4],
       [ 7, 46, 16, 36]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [93]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_five = np.random.randint(0,10,size=(3,5))
array_six = np.random.randint(0,10,size=(3,5))

In [94]:
array_five

array([[6, 7, 0, 5, 7],
       [4, 3, 1, 5, 5],
       [0, 8, 5, 2, 3]])

In [95]:
array_six

array([[3, 2, 9, 2, 2],
       [3, 6, 3, 8, 0],
       [7, 6, 1, 7, 0]])

In [96]:
# Compare the two arrays with '>'
array_five > array_six

array([[ True,  True, False,  True,  True],
       [ True, False, False, False,  True],
       [False,  True,  True, False,  True]])

What happens when you compare the arrays with `>`?

In [97]:
# Compare the two arrays with '>='
array_five >= array_six

array([[ True,  True, False,  True,  True],
       [ True, False, False, False,  True],
       [False,  True,  True, False,  True]])

In [131]:
# Find which elements of the first array are greater than 7
array_five > 7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [98]:
# Which parts of each array are equal? (try using '==')
array_five == array_six

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [102]:
# Sort one of the arrays you just created in ascending order
np.sort(array_five)

array([[0, 5, 6, 7, 7],
       [1, 3, 4, 5, 5],
       [0, 2, 3, 5, 8]])

In [104]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_five)

array([[2, 3, 0, 1, 4],
       [2, 1, 0, 3, 4],
       [0, 3, 4, 2, 1]], dtype=int64)

In [105]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_five)

11

In [106]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_five)

2

In [107]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_five, axis=1)

array([1, 3, 1], dtype=int64)

In [108]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(array_five, axis=0)

array([0, 2, 2, 0, 0], dtype=int64)

In [111]:
# Create an array of normally distributed random numbers
array_seven = np.random.normal(3, 2.5, size=(2, 4))
# np.random.randn = sama saja
array_seven

array([[5.50121402, 3.38105216, 1.49650689, 0.88346411],
       [5.04038181, 4.17926823, 2.28627675, 5.66323117]])

In [112]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.